baseURL = 'https://blog.nemesiscodex.org/'
languageCode = 'en-us'
title = "Nemesiscodex's Blog"
theme = "hello-friend-ng"

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  unsafe = true

[params]
  enableGlobalLanguageMenu = true
  disableReadOtherPosts = false
  enableSharingButtons = true

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
  [taxonomies]
    tag      = "tags"
    category = "categories"
  [social]
    name = "X"
    url = "https://x.com/nemesiscodex"
